version: "2"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./data/mongo:/data/db"

  redis:
    image: bitnami/redis:5.0.5
    restart: always
    container_name: redis_ext
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/bitnami/redis/data
